language: node_js

node_js:
  - node  # latest

os:
  - osx
  - linux

before_install:
  - npm i -g codecov

install:
  - npm i

script:
  - npm run test

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
